CXX = g++
CPPFLAGS = -std=c++20 -g -Wall

all: prims kruskals-disjoint-sets

prims: prims.cc
	   $(CXX) $(CPPFLAGS) $^ -o $@

kruskals-disjoint-sets: kruskals-disjoint-sets.cc
	   $(CXX) $(CPPFLAGS) $^ -o $@
